# deposition settings
deposition_element: O
deposition_type: MONATOMIC
deposition_height_Angstroms: 4
deposition_temperature_Kelvin: 300
minimum_deposition_velocity_metres_per_second: 25
num_deposited_per_iteration: 1
relaxation_time_picoseconds: 0.1
deposition_time_picoseconds: 0.4
substrate_xyz_file: settings/substrate.xyz
bonding_distance_cutoff_Angstroms: 4
maximum_sequential_failures: 5
maximum_total_iterations: 10

driver_settings:
    name: GULP
    path_to_binary: /Users/martin/work/repos/gulp-5.0/Src/gulp
    path_to_input_template: settings/gulp_input_template.txt
    velocity_scaling_from_metres_per_second: 0.01  # convert to Angstroms/ps
    GULP_LIB: /Users/martin/work/repos/gulp-5.0/Libraries/ # /home/595/mjc595/gulp-5.0/Libraries/
    # extra values to replace in input template
    library_name: streitzmintmire
    temperature_of_system: 300
    equilibration_time_picoseconds: 0.0
    md_time_step_ps: 0.001
    sample_rate_ps: 0.01
    write_rate_ps: 0.01

simulation_cell:
    a: 8.08
    b: 8.08
    c: 200
    alpha: 90
    beta: 90
    gamma: 90
