name: LAMMPS
temperature_of_system: 300
md_timestep_fs: 1.0
write_data_every_n_steps: 10
relaxation_num_steps: 100
deposition_num_steps: 500
velocity_scaling_from_metres_per_second: 0.00001  # TODO check this value
potential_file: settings/potential.reax
atomic_species:
  - Al
  - O
atomic_masses:
  - 26.9815386
  - 15.9994
