# software data
name: LAMMPS
path_to_binary: /Users/martin/work/repos/lammps/src/lmp_serial
path_to_input_template: settings/lammps_input_template.txt

# potential information (order of elements and masses must match)
elements_in_potential: Al O
atomic_masses:
- 26.9815386
- 15.9994

# molecular dynamics settings - required conversions change depending on LAMMPS "units" command
velocity_scaling_from_metres_per_second: 0.00001  # convert to Angstroms/fs
timestep_scaling_from_ps: 1000  # convert to femtoseconds

# extra values to replace in input template
potential_file: settings/Hong_and_van_Duin_2015_Al_O.reaxff
temperature_of_system: 300
molecular_dynamics_timestep: 1.0
write_data_every_n_steps: 10