# 1. Deposition settings (physics)
deposition_element: O
deposition_type: MONATOMIC
deposition_height_Angstroms: 10
deposition_temperature_Kelvin: 300
min_velocity_metres_per_second: 25
num_deposited_per_iteration: 1
relaxation_time_picoseconds: 0.1
deposition_time_picoseconds: 0.4
substrate_xyz_file: settings/substrate.xyz
max_sequential_failures: 5
max_total_iterations: 10
position_distribution: uniform
velocity_distribution: gaussian
velocity_distribution_parameters: [300, 1e-25, 0]  # temperature, atom weight, centre
postprocessing:
    num_neighbours: [1, 9]  # min num neighbours, bonding distance
    shift_to_origin: 1

# 2. Driver settings
driver_settings:
    name: LAMMPS
    path_to_binary: /Users/martin/work/repos/lammps/src/lmp_serial
    path_to_input_template: settings/lammps_input_template.txt
    velocity_scaling_from_metres_per_second: 0.00001  # convert to Angstroms/fs
    timestep_scaling_from_picoseconds: 1000  # convert to femtoseconds
    elements_in_potential: Al O # potential information (order of elements and masses must match)
    atomic_masses:
        - 26.9815386
        - 15.9994
    # additional values to replace in input template
    potential_file: settings/Hong_and_van_Duin_2015_Al_O.reaxff
    temperature_of_system: 300
    molecular_dynamics_timestep: 1.0
    write_data_every_n_steps: 10

# 3. Simulation cell
simulation_cell:
    a: 8.08
    b: 8.08
    c: 200
    alpha: 90
    beta: 90
    gamma: 90
