# paths to additional settings
driver_settings: settings/lammps_settings.yaml
simulation_cell_data: settings/simulation_cell.yaml
substrate_xyz_file: settings/substrate.xyz

# deposition settings (physics)
deposition_type: monatomic
deposition_element: O
deposition_height_Angstroms: 10
deposition_temperature_Kelvin: 300
minimum_deposition_velocity_metres_per_second: 25

# deposition settings (numeric)
bonding_distance_cutoff_Angstroms: 4
num_deposited_per_iteration: 1
maximum_total_iterations: 10
maximum_sequential_failures: 5

